// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example/example.proto

package example

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/wores/protoc-gen-pipeline/pipeline"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Example struct {
	Text                 string                `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	WrapText             *wrappers.StringValue `protobuf:"bytes,2,opt,name=wrapText,proto3" json:"wrapText,omitempty"`
	Texts                []string              `protobuf:"bytes,3,rep,name=texts,proto3" json:"texts,omitempty"`
	Inner                *Example_Inner        `protobuf:"bytes,4,opt,name=inner,proto3" json:"inner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Example) Reset()         { *m = Example{} }
func (m *Example) String() string { return proto.CompactTextString(m) }
func (*Example) ProtoMessage()    {}
func (*Example) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{0}
}
func (m *Example) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Example.Unmarshal(m, b)
}
func (m *Example) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Example.Marshal(b, m, deterministic)
}
func (m *Example) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Example.Merge(m, src)
}
func (m *Example) XXX_Size() int {
	return xxx_messageInfo_Example.Size(m)
}
func (m *Example) XXX_DiscardUnknown() {
	xxx_messageInfo_Example.DiscardUnknown(m)
}

var xxx_messageInfo_Example proto.InternalMessageInfo

func (m *Example) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Example) GetWrapText() *wrappers.StringValue {
	if m != nil {
		return m.WrapText
	}
	return nil
}

func (m *Example) GetTexts() []string {
	if m != nil {
		return m.Texts
	}
	return nil
}

func (m *Example) GetInner() *Example_Inner {
	if m != nil {
		return m.Inner
	}
	return nil
}

type Example_Inner struct {
	Text                 string                `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	WrapText             *wrappers.StringValue `protobuf:"bytes,2,opt,name=wrapText,proto3" json:"wrapText,omitempty"`
	Texts                []string              `protobuf:"bytes,3,rep,name=texts,proto3" json:"texts,omitempty"`
	Inner                *Example_Inner        `protobuf:"bytes,4,opt,name=inner,proto3" json:"inner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Example_Inner) Reset()         { *m = Example_Inner{} }
func (m *Example_Inner) String() string { return proto.CompactTextString(m) }
func (*Example_Inner) ProtoMessage()    {}
func (*Example_Inner) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{0, 0}
}
func (m *Example_Inner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Example_Inner.Unmarshal(m, b)
}
func (m *Example_Inner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Example_Inner.Marshal(b, m, deterministic)
}
func (m *Example_Inner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Example_Inner.Merge(m, src)
}
func (m *Example_Inner) XXX_Size() int {
	return xxx_messageInfo_Example_Inner.Size(m)
}
func (m *Example_Inner) XXX_DiscardUnknown() {
	xxx_messageInfo_Example_Inner.DiscardUnknown(m)
}

var xxx_messageInfo_Example_Inner proto.InternalMessageInfo

func (m *Example_Inner) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Example_Inner) GetWrapText() *wrappers.StringValue {
	if m != nil {
		return m.WrapText
	}
	return nil
}

func (m *Example_Inner) GetTexts() []string {
	if m != nil {
		return m.Texts
	}
	return nil
}

func (m *Example_Inner) GetInner() *Example_Inner {
	if m != nil {
		return m.Inner
	}
	return nil
}

type RemoveExample struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveExample) Reset()         { *m = RemoveExample{} }
func (m *RemoveExample) String() string { return proto.CompactTextString(m) }
func (*RemoveExample) ProtoMessage()    {}
func (*RemoveExample) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{1}
}
func (m *RemoveExample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveExample.Unmarshal(m, b)
}
func (m *RemoveExample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveExample.Marshal(b, m, deterministic)
}
func (m *RemoveExample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveExample.Merge(m, src)
}
func (m *RemoveExample) XXX_Size() int {
	return xxx_messageInfo_RemoveExample.Size(m)
}
func (m *RemoveExample) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveExample.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveExample proto.InternalMessageInfo

func (m *RemoveExample) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type ReplaceExample struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplaceExample) Reset()         { *m = ReplaceExample{} }
func (m *ReplaceExample) String() string { return proto.CompactTextString(m) }
func (*ReplaceExample) ProtoMessage()    {}
func (*ReplaceExample) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{2}
}
func (m *ReplaceExample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplaceExample.Unmarshal(m, b)
}
func (m *ReplaceExample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplaceExample.Marshal(b, m, deterministic)
}
func (m *ReplaceExample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceExample.Merge(m, src)
}
func (m *ReplaceExample) XXX_Size() int {
	return xxx_messageInfo_ReplaceExample.Size(m)
}
func (m *ReplaceExample) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceExample.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceExample proto.InternalMessageInfo

func (m *ReplaceExample) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*Example)(nil), "example.Example")
	proto.RegisterType((*Example_Inner)(nil), "example.Example.Inner")
	proto.RegisterType((*RemoveExample)(nil), "example.RemoveExample")
	proto.RegisterType((*ReplaceExample)(nil), "example.ReplaceExample")
}

func init() { proto.RegisterFile("example/example.proto", fileDescriptor_1c78cffa5d645ba4) }

var fileDescriptor_1c78cffa5d645ba4 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x52, 0x41, 0x4b, 0x84, 0x40,
	0x14, 0x66, 0x74, 0xdd, 0xd5, 0x29, 0xf7, 0x30, 0x50, 0x89, 0x6c, 0x21, 0x42, 0x20, 0xb1, 0x8e,
	0x50, 0xfd, 0x02, 0xa1, 0x43, 0x57, 0x8b, 0x0e, 0xdd, 0x54, 0x5e, 0x26, 0xa8, 0x33, 0x8c, 0xda,
	0xee, 0x7f, 0xf1, 0x9f, 0xd8, 0x4f, 0xeb, 0x12, 0x3a, 0x2a, 0xec, 0xa1, 0x7b, 0xa7, 0x99, 0x79,
	0xdf, 0xf7, 0xbd, 0xf7, 0x7d, 0xcc, 0xc3, 0x17, 0x70, 0x8c, 0x4b, 0x5e, 0x40, 0x30, 0x9d, 0x94,
	0x0b, 0xd6, 0x30, 0xb2, 0x99, 0x9e, 0xf6, 0x4d, 0xc6, 0x58, 0x56, 0x40, 0x30, 0x96, 0x93, 0xf6,
	0x23, 0x38, 0x88, 0x98, 0x73, 0x10, 0xb5, 0x24, 0xda, 0x57, 0x3c, 0xe7, 0x50, 0xe4, 0x15, 0x04,
	0xf3, 0x45, 0x02, 0xee, 0x8f, 0x82, 0x37, 0x4f, 0xb2, 0x09, 0xd9, 0xe1, 0x55, 0x03, 0xc7, 0xc6,
	0x42, 0x0e, 0xf2, 0x8c, 0x50, 0xef, 0x3b, 0x73, 0x45, 0x14, 0x5d, 0x89, 0xc6, 0x2a, 0x09, 0xb1,
	0x3e, 0x34, 0x7d, 0x1d, 0x18, 0x8a, 0x83, 0xbc, 0xb3, 0xfb, 0x1d, 0x95, 0x53, 0xe9, 0x3c, 0x95,
	0xbe, 0x34, 0x22, 0xaf, 0xb2, 0xb7, 0xb8, 0x68, 0x61, 0xd1, 0xa3, 0x68, 0xd1, 0x11, 0x17, 0x6b,
	0x43, 0xaf, 0xda, 0x52, 0x1d, 0xd5, 0x33, 0xc2, 0xf3, 0xbe, 0x33, 0x75, 0x7b, 0x8d, 0x25, 0x4d,
	0x42, 0x64, 0x8f, 0xb5, 0xbc, 0xaa, 0x40, 0x58, 0xab, 0x71, 0xc8, 0x25, 0x9d, 0x23, 0x4f, 0x36,
	0xe9, 0xf3, 0x80, 0x46, 0x92, 0x64, 0x7f, 0x23, 0xac, 0x8d, 0x85, 0x3f, 0xdc, 0xab, 0xff, 0xd9,
	0xbd, 0x4b, 0xb1, 0x19, 0x41, 0xc9, 0xbe, 0x60, 0xfe, 0x82, 0xeb, 0x93, 0x10, 0x46, 0xdf, 0x99,
	0x1a, 0x51, 0x09, 0xf2, 0x65, 0x0a, 0xf7, 0x11, 0x6f, 0x23, 0xe0, 0x45, 0x9c, 0x2e, 0x02, 0xf7,
	0x44, 0xb0, 0xed, 0x3b, 0x13, 0x93, 0xc1, 0x14, 0xba, 0x23, 0xe8, 0x56, 0xaa, 0x42, 0xfa, 0xbe,
	0xcf, 0xf2, 0xe6, 0xb3, 0x4d, 0x68, 0xca, 0xca, 0xe0, 0xc0, 0x04, 0xd4, 0x72, 0x51, 0x52, 0x3f,
	0x83, 0xca, 0x5f, 0x56, 0x63, 0xb2, 0x9a, 0xac, 0x47, 0xf0, 0xe1, 0x37, 0x00, 0x00, 0xff, 0xff,
	0xef, 0x07, 0x3f, 0x20, 0x75, 0x02, 0x00, 0x00,
}
