// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example/string_example.proto

package example

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/wores/protoc-gen-pipeline/pipeline"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StringAllExample struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringAllExample) Reset()         { *m = StringAllExample{} }
func (m *StringAllExample) String() string { return proto.CompactTextString(m) }
func (*StringAllExample) ProtoMessage()    {}
func (*StringAllExample) Descriptor() ([]byte, []int) {
	return fileDescriptor_bed2db4ecae0be2c, []int{0}
}
func (m *StringAllExample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringAllExample.Unmarshal(m, b)
}
func (m *StringAllExample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringAllExample.Marshal(b, m, deterministic)
}
func (m *StringAllExample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringAllExample.Merge(m, src)
}
func (m *StringAllExample) XXX_Size() int {
	return xxx_messageInfo_StringAllExample.Size(m)
}
func (m *StringAllExample) XXX_DiscardUnknown() {
	xxx_messageInfo_StringAllExample.DiscardUnknown(m)
}

var xxx_messageInfo_StringAllExample proto.InternalMessageInfo

func (m *StringAllExample) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type StringTrimExample struct {
	Text                 string                   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	WrapText             *wrappers.StringValue    `protobuf:"bytes,2,opt,name=wrapText,proto3" json:"wrapText,omitempty"`
	Texts                []string                 `protobuf:"bytes,3,rep,name=texts,proto3" json:"texts,omitempty"`
	Inner                *StringTrimExample_Inner `protobuf:"bytes,4,opt,name=inner,proto3" json:"inner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *StringTrimExample) Reset()         { *m = StringTrimExample{} }
func (m *StringTrimExample) String() string { return proto.CompactTextString(m) }
func (*StringTrimExample) ProtoMessage()    {}
func (*StringTrimExample) Descriptor() ([]byte, []int) {
	return fileDescriptor_bed2db4ecae0be2c, []int{1}
}
func (m *StringTrimExample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringTrimExample.Unmarshal(m, b)
}
func (m *StringTrimExample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringTrimExample.Marshal(b, m, deterministic)
}
func (m *StringTrimExample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringTrimExample.Merge(m, src)
}
func (m *StringTrimExample) XXX_Size() int {
	return xxx_messageInfo_StringTrimExample.Size(m)
}
func (m *StringTrimExample) XXX_DiscardUnknown() {
	xxx_messageInfo_StringTrimExample.DiscardUnknown(m)
}

var xxx_messageInfo_StringTrimExample proto.InternalMessageInfo

func (m *StringTrimExample) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *StringTrimExample) GetWrapText() *wrappers.StringValue {
	if m != nil {
		return m.WrapText
	}
	return nil
}

func (m *StringTrimExample) GetTexts() []string {
	if m != nil {
		return m.Texts
	}
	return nil
}

func (m *StringTrimExample) GetInner() *StringTrimExample_Inner {
	if m != nil {
		return m.Inner
	}
	return nil
}

type StringTrimExample_Inner struct {
	Text                 string                   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	WrapText             *wrappers.StringValue    `protobuf:"bytes,2,opt,name=wrapText,proto3" json:"wrapText,omitempty"`
	Texts                []string                 `protobuf:"bytes,3,rep,name=texts,proto3" json:"texts,omitempty"`
	Inner                *StringTrimExample_Inner `protobuf:"bytes,4,opt,name=inner,proto3" json:"inner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *StringTrimExample_Inner) Reset()         { *m = StringTrimExample_Inner{} }
func (m *StringTrimExample_Inner) String() string { return proto.CompactTextString(m) }
func (*StringTrimExample_Inner) ProtoMessage()    {}
func (*StringTrimExample_Inner) Descriptor() ([]byte, []int) {
	return fileDescriptor_bed2db4ecae0be2c, []int{1, 0}
}
func (m *StringTrimExample_Inner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringTrimExample_Inner.Unmarshal(m, b)
}
func (m *StringTrimExample_Inner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringTrimExample_Inner.Marshal(b, m, deterministic)
}
func (m *StringTrimExample_Inner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringTrimExample_Inner.Merge(m, src)
}
func (m *StringTrimExample_Inner) XXX_Size() int {
	return xxx_messageInfo_StringTrimExample_Inner.Size(m)
}
func (m *StringTrimExample_Inner) XXX_DiscardUnknown() {
	xxx_messageInfo_StringTrimExample_Inner.DiscardUnknown(m)
}

var xxx_messageInfo_StringTrimExample_Inner proto.InternalMessageInfo

func (m *StringTrimExample_Inner) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *StringTrimExample_Inner) GetWrapText() *wrappers.StringValue {
	if m != nil {
		return m.WrapText
	}
	return nil
}

func (m *StringTrimExample_Inner) GetTexts() []string {
	if m != nil {
		return m.Texts
	}
	return nil
}

func (m *StringTrimExample_Inner) GetInner() *StringTrimExample_Inner {
	if m != nil {
		return m.Inner
	}
	return nil
}

type StringRemoveExample struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringRemoveExample) Reset()         { *m = StringRemoveExample{} }
func (m *StringRemoveExample) String() string { return proto.CompactTextString(m) }
func (*StringRemoveExample) ProtoMessage()    {}
func (*StringRemoveExample) Descriptor() ([]byte, []int) {
	return fileDescriptor_bed2db4ecae0be2c, []int{2}
}
func (m *StringRemoveExample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringRemoveExample.Unmarshal(m, b)
}
func (m *StringRemoveExample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringRemoveExample.Marshal(b, m, deterministic)
}
func (m *StringRemoveExample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringRemoveExample.Merge(m, src)
}
func (m *StringRemoveExample) XXX_Size() int {
	return xxx_messageInfo_StringRemoveExample.Size(m)
}
func (m *StringRemoveExample) XXX_DiscardUnknown() {
	xxx_messageInfo_StringRemoveExample.DiscardUnknown(m)
}

var xxx_messageInfo_StringRemoveExample proto.InternalMessageInfo

func (m *StringRemoveExample) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type StringReplaceExample struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringReplaceExample) Reset()         { *m = StringReplaceExample{} }
func (m *StringReplaceExample) String() string { return proto.CompactTextString(m) }
func (*StringReplaceExample) ProtoMessage()    {}
func (*StringReplaceExample) Descriptor() ([]byte, []int) {
	return fileDescriptor_bed2db4ecae0be2c, []int{3}
}
func (m *StringReplaceExample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringReplaceExample.Unmarshal(m, b)
}
func (m *StringReplaceExample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringReplaceExample.Marshal(b, m, deterministic)
}
func (m *StringReplaceExample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringReplaceExample.Merge(m, src)
}
func (m *StringReplaceExample) XXX_Size() int {
	return xxx_messageInfo_StringReplaceExample.Size(m)
}
func (m *StringReplaceExample) XXX_DiscardUnknown() {
	xxx_messageInfo_StringReplaceExample.DiscardUnknown(m)
}

var xxx_messageInfo_StringReplaceExample proto.InternalMessageInfo

func (m *StringReplaceExample) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type StringOmissionExample struct {
	Left                 string   `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Center               string   `protobuf:"bytes,2,opt,name=center,proto3" json:"center,omitempty"`
	Right                string   `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringOmissionExample) Reset()         { *m = StringOmissionExample{} }
func (m *StringOmissionExample) String() string { return proto.CompactTextString(m) }
func (*StringOmissionExample) ProtoMessage()    {}
func (*StringOmissionExample) Descriptor() ([]byte, []int) {
	return fileDescriptor_bed2db4ecae0be2c, []int{4}
}
func (m *StringOmissionExample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringOmissionExample.Unmarshal(m, b)
}
func (m *StringOmissionExample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringOmissionExample.Marshal(b, m, deterministic)
}
func (m *StringOmissionExample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringOmissionExample.Merge(m, src)
}
func (m *StringOmissionExample) XXX_Size() int {
	return xxx_messageInfo_StringOmissionExample.Size(m)
}
func (m *StringOmissionExample) XXX_DiscardUnknown() {
	xxx_messageInfo_StringOmissionExample.DiscardUnknown(m)
}

var xxx_messageInfo_StringOmissionExample proto.InternalMessageInfo

func (m *StringOmissionExample) GetLeft() string {
	if m != nil {
		return m.Left
	}
	return ""
}

func (m *StringOmissionExample) GetCenter() string {
	if m != nil {
		return m.Center
	}
	return ""
}

func (m *StringOmissionExample) GetRight() string {
	if m != nil {
		return m.Right
	}
	return ""
}

func init() {
	proto.RegisterType((*StringAllExample)(nil), "example.StringAllExample")
	proto.RegisterType((*StringTrimExample)(nil), "example.StringTrimExample")
	proto.RegisterType((*StringTrimExample_Inner)(nil), "example.StringTrimExample.Inner")
	proto.RegisterType((*StringRemoveExample)(nil), "example.StringRemoveExample")
	proto.RegisterType((*StringReplaceExample)(nil), "example.StringReplaceExample")
	proto.RegisterType((*StringOmissionExample)(nil), "example.StringOmissionExample")
}

func init() { proto.RegisterFile("example/string_example.proto", fileDescriptor_bed2db4ecae0be2c) }

var fileDescriptor_bed2db4ecae0be2c = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x93, 0xcf, 0x8a, 0xd4, 0x40,
	0x10, 0xc6, 0xe9, 0x64, 0x32, 0x9b, 0xa9, 0x35, 0xe2, 0x96, 0x8a, 0x31, 0x8e, 0x3a, 0x04, 0x96,
	0x1d, 0xc5, 0x49, 0xc0, 0x15, 0x0f, 0xde, 0x1c, 0x10, 0xf1, 0x24, 0xc4, 0xc5, 0x83, 0x7f, 0x90,
	0x99, 0xa1, 0x36, 0xdb, 0xd0, 0x49, 0xc7, 0x4e, 0xc6, 0xdd, 0xa3, 0xcf, 0xe0, 0x4d, 0x72, 0xf7,
	0x21, 0x72, 0xf7, 0x45, 0x7c, 0x12, 0x49, 0x3a, 0x1d, 0x18, 0x5c, 0x1f, 0x60, 0x6f, 0xe9, 0xae,
	0xef, 0xf7, 0xa5, 0xbe, 0xea, 0x6e, 0x98, 0xd2, 0xc5, 0x2a, 0x2b, 0x04, 0xc5, 0x65, 0xa5, 0x78,
	0x9e, 0x7e, 0xe9, 0x97, 0x51, 0xa1, 0x64, 0x25, 0x71, 0xaf, 0x5f, 0x06, 0x0f, 0x52, 0x29, 0x53,
	0x41, 0x71, 0xb7, 0xbd, 0xde, 0x9e, 0xc6, 0xe7, 0x6a, 0x55, 0x14, 0xa4, 0x4a, 0x2d, 0x0c, 0xee,
	0x14, 0xbc, 0x20, 0xc1, 0x73, 0x8a, 0xcd, 0x87, 0x2e, 0x84, 0xaf, 0xe1, 0xc6, 0xbb, 0xce, 0xf9,
	0xa5, 0x10, 0xaf, 0xb4, 0x19, 0x1e, 0xc3, 0xa8, 0xa2, 0x8b, 0xca, 0x67, 0x33, 0x36, 0x9f, 0x2c,
	0x1f, 0x36, 0xb5, 0x77, 0x0f, 0xef, 0xba, 0x0c, 0xd9, 0xd7, 0x60, 0x0f, 0xd8, 0x11, 0x5a, 0x9f,
	0xc2, 0x70, 0xe2, 0x02, 0xda, 0x1f, 0x17, 0x9f, 0x7d, 0x96, 0x74, 0xe2, 0xf0, 0xa7, 0x0d, 0x07,
	0xda, 0xe9, 0x44, 0xf1, 0xcc, 0x58, 0x4d, 0x77, 0xac, 0xdc, 0xa6, 0xf6, 0x46, 0x68, 0xb9, 0x96,
	0x66, 0x70, 0x09, 0x6e, 0xdb, 0xe7, 0x49, 0xab, 0xb0, 0x66, 0x6c, 0xbe, 0xff, 0x74, 0x1a, 0xe9,
	0x20, 0x91, 0x09, 0x12, 0x69, 0xcf, 0xf7, 0x2b, 0xb1, 0xa5, 0x81, 0x67, 0xc9, 0xc0, 0x61, 0x08,
	0x4e, 0xeb, 0x55, 0xfa, 0xf6, 0xcc, 0x9e, 0x4f, 0x96, 0xd7, 0x9a, 0xda, 0x73, 0x83, 0x31, 0x68,
	0x99, 0x2e, 0xe1, 0x73, 0x70, 0x78, 0x9e, 0x93, 0xf2, 0x47, 0xdd, 0x4f, 0x66, 0x91, 0x99, 0xe2,
	0x3f, 0x0d, 0x47, 0x6f, 0x5a, 0x5d, 0xa2, 0xe5, 0xc1, 0x6f, 0x06, 0x4e, 0xb7, 0xf1, 0x9f, 0x1c,
	0xf6, 0xd5, 0xc8, 0x11, 0x3e, 0x83, 0x9b, 0x5a, 0x91, 0x50, 0x26, 0xbf, 0x91, 0x39, 0x9c, 0xfb,
	0x3b, 0xa1, 0x26, 0x4d, 0xed, 0x39, 0x68, 0x23, 0x5b, 0xf4, 0x27, 0xfa, 0x02, 0x6e, 0x19, 0xaa,
	0x10, 0xab, 0xcd, 0x80, 0x85, 0x3b, 0xd8, 0xf5, 0xa6, 0xf6, 0x00, 0xdb, 0x56, 0xd9, 0x63, 0x64,
	0x87, 0x3d, 0xfb, 0x83, 0xc1, 0x6d, 0x0d, 0xbf, 0xcd, 0x78, 0x59, 0x72, 0x99, 0x1b, 0xfa, 0x10,
	0x46, 0x82, 0x4e, 0x0d, 0x7d, 0xd0, 0xd4, 0x9e, 0x87, 0xfb, 0xfa, 0x3a, 0xfd, 0xf9, 0xfe, 0xab,
	0xbd, 0x4e, 0x6d, 0x19, 0x1f, 0xc1, 0x78, 0x43, 0x79, 0x45, 0xaa, 0x1b, 0xe8, 0x25, 0x42, 0x2b,
	0xe9, 0x05, 0x78, 0x04, 0x8e, 0xe2, 0xe9, 0x59, 0xe5, 0xdb, 0x97, 0x2b, 0xed, 0x44, 0xd7, 0x97,
	0xd1, 0x87, 0x27, 0x29, 0xaf, 0xce, 0xb6, 0xeb, 0x68, 0x23, 0xb3, 0xf8, 0x5c, 0x2a, 0x2a, 0xf5,
	0x83, 0xd9, 0x2c, 0x52, 0xca, 0x17, 0xc3, 0x13, 0xe9, 0xa7, 0xba, 0x1e, 0x77, 0xc5, 0xe3, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xd0, 0xa6, 0xb5, 0x84, 0x03, 0x00, 0x00,
}
