// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pipeline/pipeline.proto

package pipeline

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TrimType はトリムの定義。
type TrimType int32

const (
	// 両サイドをトリムする。
	TrimType_TrimTypeBoth TrimType = 1
	// 左サイドをトリムする。
	TrimType_TrimTypeLeft TrimType = 2
	// 右サイドをトリムする。
	TrimType_TrimTypeRight TrimType = 3
)

var TrimType_name = map[int32]string{
	1: "TrimTypeBoth",
	2: "TrimTypeLeft",
	3: "TrimTypeRight",
}

var TrimType_value = map[string]int32{
	"TrimTypeBoth":  1,
	"TrimTypeLeft":  2,
	"TrimTypeRight": 3,
}

func (x TrimType) Enum() *TrimType {
	p := new(TrimType)
	*p = x
	return p
}

func (x TrimType) String() string {
	return proto.EnumName(TrimType_name, int32(x))
}

func (x *TrimType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TrimType_value, data, "TrimType")
	if err != nil {
		return err
	}
	*x = TrimType(value)
	return nil
}

func (TrimType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_26c1246e548f11df, []int{0}
}

type FieldProcesses struct {
	Message *MessageProcesses `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	// Types that are valid to be assigned to Type:
	//	*FieldProcesses_String_
	//	*FieldProcesses_Repeated
	Type                 isFieldProcesses_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FieldProcesses) Reset()         { *m = FieldProcesses{} }
func (m *FieldProcesses) String() string { return proto.CompactTextString(m) }
func (*FieldProcesses) ProtoMessage()    {}
func (*FieldProcesses) Descriptor() ([]byte, []int) {
	return fileDescriptor_26c1246e548f11df, []int{0}
}

func (m *FieldProcesses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldProcesses.Unmarshal(m, b)
}
func (m *FieldProcesses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldProcesses.Marshal(b, m, deterministic)
}
func (m *FieldProcesses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldProcesses.Merge(m, src)
}
func (m *FieldProcesses) XXX_Size() int {
	return xxx_messageInfo_FieldProcesses.Size(m)
}
func (m *FieldProcesses) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldProcesses.DiscardUnknown(m)
}

var xxx_messageInfo_FieldProcesses proto.InternalMessageInfo

func (m *FieldProcesses) GetMessage() *MessageProcesses {
	if m != nil {
		return m.Message
	}
	return nil
}

type isFieldProcesses_Type interface {
	isFieldProcesses_Type()
}

type FieldProcesses_String_ struct {
	String_ *StringProcesses `protobuf:"bytes,2,opt,name=string,oneof"`
}

type FieldProcesses_Repeated struct {
	Repeated *RepeatedProcesses `protobuf:"bytes,3,opt,name=repeated,oneof"`
}

func (*FieldProcesses_String_) isFieldProcesses_Type() {}

func (*FieldProcesses_Repeated) isFieldProcesses_Type() {}

func (m *FieldProcesses) GetType() isFieldProcesses_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *FieldProcesses) GetString_() *StringProcesses {
	if x, ok := m.GetType().(*FieldProcesses_String_); ok {
		return x.String_
	}
	return nil
}

func (m *FieldProcesses) GetRepeated() *RepeatedProcesses {
	if x, ok := m.GetType().(*FieldProcesses_Repeated); ok {
		return x.Repeated
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FieldProcesses) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FieldProcesses_String_)(nil),
		(*FieldProcesses_Repeated)(nil),
	}
}

type StringProcesses struct {
	// トリムする。
	Trim *TrimType `protobuf:"varint,1,opt,name=trim,enum=pipeline.TrimType" json:"trim,omitempty"`
	// 指定した文字を削除する。
	Remove *string `protobuf:"bytes,2,opt,name=remove" json:"remove,omitempty"`
	// 指定した文字を指定した文字へリプレイスする。
	Replace              *StringReplace `protobuf:"bytes,3,opt,name=replace" json:"replace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StringProcesses) Reset()         { *m = StringProcesses{} }
func (m *StringProcesses) String() string { return proto.CompactTextString(m) }
func (*StringProcesses) ProtoMessage()    {}
func (*StringProcesses) Descriptor() ([]byte, []int) {
	return fileDescriptor_26c1246e548f11df, []int{1}
}

func (m *StringProcesses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringProcesses.Unmarshal(m, b)
}
func (m *StringProcesses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringProcesses.Marshal(b, m, deterministic)
}
func (m *StringProcesses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringProcesses.Merge(m, src)
}
func (m *StringProcesses) XXX_Size() int {
	return xxx_messageInfo_StringProcesses.Size(m)
}
func (m *StringProcesses) XXX_DiscardUnknown() {
	xxx_messageInfo_StringProcesses.DiscardUnknown(m)
}

var xxx_messageInfo_StringProcesses proto.InternalMessageInfo

func (m *StringProcesses) GetTrim() TrimType {
	if m != nil && m.Trim != nil {
		return *m.Trim
	}
	return TrimType_TrimTypeBoth
}

func (m *StringProcesses) GetRemove() string {
	if m != nil && m.Remove != nil {
		return *m.Remove
	}
	return ""
}

func (m *StringProcesses) GetReplace() *StringReplace {
	if m != nil {
		return m.Replace
	}
	return nil
}

type StringReplace struct {
	Old                  *string  `protobuf:"bytes,1,req,name=old" json:"old,omitempty"`
	New                  *string  `protobuf:"bytes,2,req,name=new" json:"new,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringReplace) Reset()         { *m = StringReplace{} }
func (m *StringReplace) String() string { return proto.CompactTextString(m) }
func (*StringReplace) ProtoMessage()    {}
func (*StringReplace) Descriptor() ([]byte, []int) {
	return fileDescriptor_26c1246e548f11df, []int{2}
}

func (m *StringReplace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringReplace.Unmarshal(m, b)
}
func (m *StringReplace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringReplace.Marshal(b, m, deterministic)
}
func (m *StringReplace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringReplace.Merge(m, src)
}
func (m *StringReplace) XXX_Size() int {
	return xxx_messageInfo_StringReplace.Size(m)
}
func (m *StringReplace) XXX_DiscardUnknown() {
	xxx_messageInfo_StringReplace.DiscardUnknown(m)
}

var xxx_messageInfo_StringReplace proto.InternalMessageInfo

func (m *StringReplace) GetOld() string {
	if m != nil && m.Old != nil {
		return *m.Old
	}
	return ""
}

func (m *StringReplace) GetNew() string {
	if m != nil && m.New != nil {
		return *m.New
	}
	return ""
}

type RepeatedProcesses struct {
	Items                *FieldProcesses `protobuf:"bytes,1,opt,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RepeatedProcesses) Reset()         { *m = RepeatedProcesses{} }
func (m *RepeatedProcesses) String() string { return proto.CompactTextString(m) }
func (*RepeatedProcesses) ProtoMessage()    {}
func (*RepeatedProcesses) Descriptor() ([]byte, []int) {
	return fileDescriptor_26c1246e548f11df, []int{3}
}

func (m *RepeatedProcesses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedProcesses.Unmarshal(m, b)
}
func (m *RepeatedProcesses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedProcesses.Marshal(b, m, deterministic)
}
func (m *RepeatedProcesses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedProcesses.Merge(m, src)
}
func (m *RepeatedProcesses) XXX_Size() int {
	return xxx_messageInfo_RepeatedProcesses.Size(m)
}
func (m *RepeatedProcesses) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedProcesses.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedProcesses proto.InternalMessageInfo

func (m *RepeatedProcesses) GetItems() *FieldProcesses {
	if m != nil {
		return m.Items
	}
	return nil
}

type MessageProcesses struct {
	// 処理をskipする。
	Skip                 *bool    `protobuf:"varint,1,opt,name=skip" json:"skip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageProcesses) Reset()         { *m = MessageProcesses{} }
func (m *MessageProcesses) String() string { return proto.CompactTextString(m) }
func (*MessageProcesses) ProtoMessage()    {}
func (*MessageProcesses) Descriptor() ([]byte, []int) {
	return fileDescriptor_26c1246e548f11df, []int{4}
}

func (m *MessageProcesses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageProcesses.Unmarshal(m, b)
}
func (m *MessageProcesses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageProcesses.Marshal(b, m, deterministic)
}
func (m *MessageProcesses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageProcesses.Merge(m, src)
}
func (m *MessageProcesses) XXX_Size() int {
	return xxx_messageInfo_MessageProcesses.Size(m)
}
func (m *MessageProcesses) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageProcesses.DiscardUnknown(m)
}

var xxx_messageInfo_MessageProcesses proto.InternalMessageInfo

func (m *MessageProcesses) GetSkip() bool {
	if m != nil && m.Skip != nil {
		return *m.Skip
	}
	return false
}

var E_Processes = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldProcesses)(nil),
	Field:         27063,
	Name:          "pipeline.processes",
	Tag:           "bytes,27063,opt,name=processes",
	Filename:      "pipeline/pipeline.proto",
}

func init() {
	proto.RegisterEnum("pipeline.TrimType", TrimType_name, TrimType_value)
	proto.RegisterType((*FieldProcesses)(nil), "pipeline.FieldProcesses")
	proto.RegisterType((*StringProcesses)(nil), "pipeline.StringProcesses")
	proto.RegisterType((*StringReplace)(nil), "pipeline.StringReplace")
	proto.RegisterType((*RepeatedProcesses)(nil), "pipeline.RepeatedProcesses")
	proto.RegisterType((*MessageProcesses)(nil), "pipeline.MessageProcesses")
	proto.RegisterExtension(E_Processes)
}

func init() { proto.RegisterFile("pipeline/pipeline.proto", fileDescriptor_26c1246e548f11df) }

var fileDescriptor_26c1246e548f11df = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x26, 0x69, 0xe9, 0xa6, 0x03, 0xbb, 0x64, 0x7d, 0x60, 0x43, 0x11, 0x52, 0x95, 0x43, 0x55,
	0x21, 0x35, 0x11, 0x2d, 0x17, 0xb8, 0x51, 0x24, 0xc4, 0x01, 0x04, 0x32, 0x95, 0x90, 0xb8, 0xb5,
	0xc9, 0x34, 0xb5, 0x48, 0x62, 0xcb, 0x76, 0xa9, 0x7a, 0xe7, 0x9d, 0xb8, 0xf1, 0x12, 0xbc, 0x10,
	0xaa, 0x9d, 0x9f, 0xfe, 0x1c, 0xf6, 0x36, 0xfe, 0x7e, 0x3c, 0xdf, 0xd8, 0x03, 0x77, 0x82, 0x09,
	0xcc, 0x59, 0x89, 0x71, 0x5d, 0x44, 0x42, 0x72, 0xcd, 0x89, 0x57, 0x9f, 0x07, 0xc3, 0x8c, 0xf3,
	0x2c, 0xc7, 0xd8, 0xe0, 0xab, 0xed, 0x3a, 0x4e, 0x51, 0x25, 0x92, 0x09, 0xcd, 0xa5, 0xd5, 0x86,
	0x7f, 0x1d, 0xb8, 0xf9, 0xc0, 0x30, 0x4f, 0xbf, 0x4a, 0x9e, 0xa0, 0x52, 0xa8, 0xc8, 0x6b, 0xb8,
	0x2a, 0x50, 0xa9, 0x65, 0x86, 0x81, 0x33, 0x74, 0xc6, 0x8f, 0xa6, 0x83, 0xa8, 0x69, 0xf0, 0xd9,
	0x12, 0x8d, 0x98, 0xd6, 0x52, 0x32, 0x83, 0x9e, 0xd2, 0x92, 0x95, 0x59, 0xe0, 0x1a, 0xd3, 0xb3,
	0xd6, 0xf4, 0xcd, 0xe0, 0x8d, 0xe7, 0xe3, 0x03, 0x5a, 0x49, 0xc9, 0x1b, 0xf0, 0x24, 0x0a, 0x5c,
	0x6a, 0x4c, 0x83, 0x8e, 0xb1, 0x3d, 0x6f, 0x6d, 0xb4, 0x62, 0x8e, 0x8d, 0x8d, 0x7c, 0xde, 0x83,
	0xae, 0xde, 0x0b, 0x0c, 0x7f, 0x3b, 0xf0, 0xe4, 0xac, 0x01, 0x19, 0x41, 0x57, 0x4b, 0x56, 0x98,
	0xf8, 0x37, 0x53, 0xd2, 0x5e, 0xb9, 0x90, 0xac, 0x58, 0xec, 0x05, 0x52, 0xc3, 0x93, 0xa7, 0xd0,
	0x93, 0x58, 0xf0, 0x5f, 0x68, 0x32, 0xf7, 0x69, 0x75, 0x22, 0xaf, 0xe0, 0x4a, 0xa2, 0xc8, 0x97,
	0x09, 0x56, 0xa9, 0xee, 0xce, 0x87, 0xa1, 0x96, 0xa6, 0xb5, 0x2e, 0x9c, 0xc1, 0xf5, 0x09, 0x43,
	0x7c, 0xe8, 0xf0, 0x3c, 0x0d, 0x9c, 0xa1, 0x3b, 0xee, 0xd3, 0x43, 0x79, 0x40, 0x4a, 0xdc, 0x05,
	0xae, 0x45, 0x4a, 0xdc, 0x85, 0xef, 0xe1, 0xf6, 0x62, 0x48, 0x12, 0xc1, 0x43, 0xa6, 0xb1, 0x50,
	0xd5, 0xe3, 0x07, 0x6d, 0xeb, 0xd3, 0x7f, 0xa2, 0x56, 0x16, 0x8e, 0xc0, 0x3f, 0xff, 0x15, 0x42,
	0xa0, 0xab, 0x7e, 0x32, 0x61, 0xae, 0xf0, 0xa8, 0xa9, 0x5f, 0xbe, 0x03, 0xaf, 0x1e, 0x9f, 0xf8,
	0xf0, 0xb8, 0xae, 0xe7, 0x5c, 0x6f, 0x7c, 0xe7, 0x18, 0xf9, 0x84, 0x6b, 0xed, 0xbb, 0xe4, 0x16,
	0xae, 0x9b, 0xe7, 0x62, 0xd9, 0x46, 0xfb, 0x9d, 0xb7, 0xdf, 0xa1, 0x2f, 0x9a, 0x1e, 0x2f, 0x22,
	0xbb, 0x5c, 0x51, 0xbd, 0x5c, 0x36, 0xdf, 0x17, 0xa1, 0x19, 0x2f, 0x55, 0xf0, 0xe7, 0xdf, 0x7d,
	0xf9, 0xdb, 0xbb, 0xe6, 0xf1, 0x8f, 0x49, 0xc6, 0xf4, 0x66, 0xbb, 0x8a, 0x12, 0x5e, 0xc4, 0x3b,
	0x2e, 0x51, 0xd9, 0x9d, 0x4d, 0x26, 0x19, 0x96, 0x93, 0x8b, 0x45, 0xff, 0x1f, 0x00, 0x00, 0xff,
	0xff, 0xc8, 0xa4, 0xb5, 0x7e, 0xfc, 0x02, 0x00, 0x00,
}
