// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pipeline/pipeline.proto

package pipeline

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TrimType はトリムの定義。
type TrimType int32

const (
	// 両サイドをトリムする。
	TrimType_TrimTypeBoth TrimType = 1
	// 左サイドをトリムする。
	TrimType_TrimTypeLeft TrimType = 2
	// 右サイドをトリムする。
	TrimType_TrimTypeRight TrimType = 3
)

var TrimType_name = map[int32]string{
	1: "TrimTypeBoth",
	2: "TrimTypeLeft",
	3: "TrimTypeRight",
}

var TrimType_value = map[string]int32{
	"TrimTypeBoth":  1,
	"TrimTypeLeft":  2,
	"TrimTypeRight": 3,
}

func (x TrimType) Enum() *TrimType {
	p := new(TrimType)
	*p = x
	return p
}

func (x TrimType) String() string {
	return proto.EnumName(TrimType_name, int32(x))
}

func (x *TrimType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TrimType_value, data, "TrimType")
	if err != nil {
		return err
	}
	*x = TrimType(value)
	return nil
}

func (TrimType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_26c1246e548f11df, []int{0}
}

type FieldProcesses struct {
	Message *MessageProcesses `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	// Types that are valid to be assigned to Type:
	//	*FieldProcesses_String_
	//	*FieldProcesses_Repeated
	Type                 isFieldProcesses_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FieldProcesses) Reset()         { *m = FieldProcesses{} }
func (m *FieldProcesses) String() string { return proto.CompactTextString(m) }
func (*FieldProcesses) ProtoMessage()    {}
func (*FieldProcesses) Descriptor() ([]byte, []int) {
	return fileDescriptor_26c1246e548f11df, []int{0}
}

func (m *FieldProcesses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldProcesses.Unmarshal(m, b)
}
func (m *FieldProcesses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldProcesses.Marshal(b, m, deterministic)
}
func (m *FieldProcesses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldProcesses.Merge(m, src)
}
func (m *FieldProcesses) XXX_Size() int {
	return xxx_messageInfo_FieldProcesses.Size(m)
}
func (m *FieldProcesses) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldProcesses.DiscardUnknown(m)
}

var xxx_messageInfo_FieldProcesses proto.InternalMessageInfo

func (m *FieldProcesses) GetMessage() *MessageProcesses {
	if m != nil {
		return m.Message
	}
	return nil
}

type isFieldProcesses_Type interface {
	isFieldProcesses_Type()
}

type FieldProcesses_String_ struct {
	String_ *StringProcesses `protobuf:"bytes,2,opt,name=string,oneof"`
}

type FieldProcesses_Repeated struct {
	Repeated *RepeatedProcesses `protobuf:"bytes,3,opt,name=repeated,oneof"`
}

func (*FieldProcesses_String_) isFieldProcesses_Type() {}

func (*FieldProcesses_Repeated) isFieldProcesses_Type() {}

func (m *FieldProcesses) GetType() isFieldProcesses_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *FieldProcesses) GetString_() *StringProcesses {
	if x, ok := m.GetType().(*FieldProcesses_String_); ok {
		return x.String_
	}
	return nil
}

func (m *FieldProcesses) GetRepeated() *RepeatedProcesses {
	if x, ok := m.GetType().(*FieldProcesses_Repeated); ok {
		return x.Repeated
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FieldProcesses) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FieldProcesses_String_)(nil),
		(*FieldProcesses_Repeated)(nil),
	}
}

type StringProcesses struct {
	ForceHoge            *bool     `protobuf:"varint,1,opt,name=forceHoge" json:"forceHoge,omitempty"`
	Trim                 *TrimType `protobuf:"varint,2,opt,name=trim,enum=pipeline.TrimType" json:"trim,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *StringProcesses) Reset()         { *m = StringProcesses{} }
func (m *StringProcesses) String() string { return proto.CompactTextString(m) }
func (*StringProcesses) ProtoMessage()    {}
func (*StringProcesses) Descriptor() ([]byte, []int) {
	return fileDescriptor_26c1246e548f11df, []int{1}
}

func (m *StringProcesses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringProcesses.Unmarshal(m, b)
}
func (m *StringProcesses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringProcesses.Marshal(b, m, deterministic)
}
func (m *StringProcesses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringProcesses.Merge(m, src)
}
func (m *StringProcesses) XXX_Size() int {
	return xxx_messageInfo_StringProcesses.Size(m)
}
func (m *StringProcesses) XXX_DiscardUnknown() {
	xxx_messageInfo_StringProcesses.DiscardUnknown(m)
}

var xxx_messageInfo_StringProcesses proto.InternalMessageInfo

func (m *StringProcesses) GetForceHoge() bool {
	if m != nil && m.ForceHoge != nil {
		return *m.ForceHoge
	}
	return false
}

func (m *StringProcesses) GetTrim() TrimType {
	if m != nil && m.Trim != nil {
		return *m.Trim
	}
	return TrimType_TrimTypeBoth
}

type RepeatedProcesses struct {
	// Items specifies the contraints to be applied to each item in the field.
	// Repeated message fields will still execute validation against each item
	// unless skip is specified here.
	Items                *FieldProcesses `protobuf:"bytes,1,opt,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RepeatedProcesses) Reset()         { *m = RepeatedProcesses{} }
func (m *RepeatedProcesses) String() string { return proto.CompactTextString(m) }
func (*RepeatedProcesses) ProtoMessage()    {}
func (*RepeatedProcesses) Descriptor() ([]byte, []int) {
	return fileDescriptor_26c1246e548f11df, []int{2}
}

func (m *RepeatedProcesses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedProcesses.Unmarshal(m, b)
}
func (m *RepeatedProcesses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedProcesses.Marshal(b, m, deterministic)
}
func (m *RepeatedProcesses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedProcesses.Merge(m, src)
}
func (m *RepeatedProcesses) XXX_Size() int {
	return xxx_messageInfo_RepeatedProcesses.Size(m)
}
func (m *RepeatedProcesses) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedProcesses.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedProcesses proto.InternalMessageInfo

func (m *RepeatedProcesses) GetItems() *FieldProcesses {
	if m != nil {
		return m.Items
	}
	return nil
}

type MessageProcesses struct {
	// Skip specifies that the validation rules of this field should not be
	// evaluated
	Skip                 *bool    `protobuf:"varint,1,opt,name=skip" json:"skip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageProcesses) Reset()         { *m = MessageProcesses{} }
func (m *MessageProcesses) String() string { return proto.CompactTextString(m) }
func (*MessageProcesses) ProtoMessage()    {}
func (*MessageProcesses) Descriptor() ([]byte, []int) {
	return fileDescriptor_26c1246e548f11df, []int{3}
}

func (m *MessageProcesses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageProcesses.Unmarshal(m, b)
}
func (m *MessageProcesses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageProcesses.Marshal(b, m, deterministic)
}
func (m *MessageProcesses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageProcesses.Merge(m, src)
}
func (m *MessageProcesses) XXX_Size() int {
	return xxx_messageInfo_MessageProcesses.Size(m)
}
func (m *MessageProcesses) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageProcesses.DiscardUnknown(m)
}

var xxx_messageInfo_MessageProcesses proto.InternalMessageInfo

func (m *MessageProcesses) GetSkip() bool {
	if m != nil && m.Skip != nil {
		return *m.Skip
	}
	return false
}

var E_Processes = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldProcesses)(nil),
	Field:         27063,
	Name:          "pipeline.processes",
	Tag:           "bytes,27063,opt,name=processes",
	Filename:      "pipeline/pipeline.proto",
}

func init() {
	proto.RegisterEnum("pipeline.TrimType", TrimType_name, TrimType_value)
	proto.RegisterType((*FieldProcesses)(nil), "pipeline.FieldProcesses")
	proto.RegisterType((*StringProcesses)(nil), "pipeline.StringProcesses")
	proto.RegisterType((*RepeatedProcesses)(nil), "pipeline.RepeatedProcesses")
	proto.RegisterType((*MessageProcesses)(nil), "pipeline.MessageProcesses")
	proto.RegisterExtension(E_Processes)
}

func init() { proto.RegisterFile("pipeline/pipeline.proto", fileDescriptor_26c1246e548f11df) }

var fileDescriptor_26c1246e548f11df = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4f, 0x4f, 0xfa, 0x40,
	0x10, 0xfd, 0x15, 0xf8, 0x61, 0x19, 0x15, 0xcb, 0x5e, 0xac, 0xa8, 0x09, 0xe9, 0x81, 0x18, 0x13,
	0xda, 0x04, 0xbd, 0xe8, 0x4d, 0x4c, 0x0c, 0x07, 0x8d, 0xa6, 0x92, 0x90, 0x78, 0x83, 0x32, 0x2c,
	0x1b, 0x69, 0x77, 0xb3, 0xbb, 0xc4, 0xf0, 0xc9, 0xbc, 0xf9, 0x25, 0xfc, 0x42, 0x26, 0xdb, 0x7f,
	0x08, 0x07, 0x6f, 0xd3, 0x37, 0xef, 0xed, 0x7b, 0x9d, 0x19, 0x38, 0x16, 0x4c, 0xe0, 0x92, 0x25,
	0x18, 0xe4, 0x85, 0x2f, 0x24, 0xd7, 0x9c, 0xd8, 0xf9, 0x77, 0xbb, 0x43, 0x39, 0xa7, 0x4b, 0x0c,
	0x0c, 0x3e, 0x5d, 0xcd, 0x83, 0x19, 0xaa, 0x48, 0x32, 0xa1, 0xb9, 0x4c, 0xb9, 0xde, 0x97, 0x05,
	0xcd, 0x07, 0x86, 0xcb, 0xd9, 0x8b, 0xe4, 0x11, 0x2a, 0x85, 0x8a, 0x5c, 0xc3, 0x5e, 0x8c, 0x4a,
	0x4d, 0x28, 0xba, 0x56, 0xc7, 0xba, 0xd8, 0xef, 0xb7, 0xfd, 0xc2, 0xe0, 0x29, 0x6d, 0x14, 0xe4,
	0x30, 0xa7, 0x92, 0x2b, 0xa8, 0x2b, 0x2d, 0x59, 0x42, 0xdd, 0x8a, 0x11, 0x9d, 0x94, 0xa2, 0x57,
	0x83, 0x17, 0x9a, 0xe1, 0xbf, 0x30, 0xa3, 0x92, 0x1b, 0xb0, 0x25, 0x0a, 0x9c, 0x68, 0x9c, 0xb9,
	0x55, 0x23, 0x3b, 0x2d, 0x65, 0x61, 0xd6, 0xd9, 0x14, 0x16, 0xf4, 0x41, 0x1d, 0x6a, 0x7a, 0x2d,
	0xd0, 0x1b, 0xc3, 0xd1, 0xd6, 0xfb, 0xe4, 0x0c, 0x1a, 0x73, 0x2e, 0x23, 0x1c, 0xf2, 0xec, 0x17,
	0xec, 0xb0, 0x04, 0x48, 0x17, 0x6a, 0x5a, 0xb2, 0xd8, 0xc4, 0x6c, 0xf6, 0x49, 0xe9, 0x37, 0x92,
	0x2c, 0x1e, 0xad, 0x05, 0x86, 0xa6, 0xef, 0xdd, 0x43, 0x6b, 0x27, 0x01, 0xf1, 0xe1, 0x3f, 0xd3,
	0x18, 0xab, 0x6c, 0x32, 0x6e, 0xa9, 0xfe, 0x3d, 0xc4, 0x30, 0xa5, 0x79, 0x5d, 0x70, 0xb6, 0x47,
	0x46, 0x08, 0xd4, 0xd4, 0x3b, 0x13, 0x59, 0x32, 0x53, 0x5f, 0xde, 0x81, 0x9d, 0xdb, 0x13, 0x07,
	0x0e, 0xf2, 0x7a, 0xc0, 0xf5, 0xc2, 0xb1, 0x36, 0x91, 0x47, 0x9c, 0x6b, 0xa7, 0x42, 0x5a, 0x70,
	0x58, 0xc4, 0x65, 0x74, 0xa1, 0x9d, 0xea, 0xed, 0x18, 0x1a, 0xa2, 0xf0, 0x38, 0xf7, 0xd3, 0xcd,
	0xfb, 0xf9, 0xe6, 0xd3, 0x7c, 0xcf, 0x42, 0x33, 0x9e, 0x28, 0xf7, 0xf3, 0xfb, 0xaf, 0xfc, 0xe5,
	0x5b, 0x83, 0xe0, 0xad, 0x47, 0x99, 0x5e, 0xac, 0xa6, 0x7e, 0xc4, 0xe3, 0xe0, 0x83, 0x4b, 0x54,
	0xe9, 0x41, 0x45, 0x3d, 0x8a, 0x49, 0x6f, 0xe7, 0x0a, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x72,
	0x4b, 0x00, 0x3b, 0x99, 0x02, 0x00, 0x00,
}
