package golang

const fileTpl = `// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: {{ .InputPath }}

package {{ pkg . }}

import (
	"bytes"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
    _ = unicode.Hiragana
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = time.Duration(0)
	_ = ptypes.DynamicAny{}
)

{{ range .AllMessages }}
	{{ template "msg" . }}
{{ end }}
`

